---
- name: Common setup on all servers
  hosts: servers
  become: true
  roles:
    - common

- name: Hardening
  hosts: servers
  become: true
  roles:
    - hardening

- name: Setup postgresql
  hosts: database
  become: true
  roles:
    - postgresql

- name: Wait for DB
  hosts: app
  gather_facts: false
  tasks:
    - name: Wait until Postgres accepts TCP on db01
      ansible.builtin.wait_for:
        host: "{{ hostvars['db01']['ansible_host'] }}"
        port: 5432
        timeout: 60
        state: started

- name: Setup app host
  hosts: app
  become: true
  roles:
    - app
